import Head from 'next/head';
// import MoreVertIcon from '@mui/icons-material/MoreVert';
import ChatList from '../components/chatList'

export default function Home() {
  return (
    <div data-theme="cupcake">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main><br />
        <h3 className="text-3xl font-bold text-center">Chat List UI</h3><br />
        <div>
          <ChatList />
        </div>
      </main>

    </div>
  )
}